version: '3.8'

services:
  app:
    build: .
    container_name: java-api
    restart: on-failure
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=280103
      - SERVER_SERVLET_CONTEXT_PATH=/api
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
      - spring.jpa.show-sql=true
      - logging.level.org.springframework.security=DEBUG
      - jwt.secret=dGVzdGVTZWNyZXRLZXlGb3JEZXZlbG9wbWVudE9ubHkxMjM0NTY3ODkw
      - jwt.access-token-expiration=604800000
    depends_on:
      - oracle-db

  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=280103
      - ORACLE_PDB_LSNR_PORT=1521
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20m
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data: